const Recommends = [
  {
    uid: "default_2017",
    name: "Vivian",
    bday: "1984/10/10",
    sex: "f",
    country: "TW",
    city:"高雄",
    intro:"努力累積我的一萬個小時!",
    languages:[{lang:"中文", level:"流利"}, {lang:"英文", level:"普通"}],
    sp: "m",
    mainPhoto: "https://loremflickr.com/640/480/taipei,woman/all",
    avatar: "https://loremflickr.com/320/240/taipei,woman/all",
  },
  {
    uid: "default_2018",
    name: "Celia",
    bday: "1981/01/10",
    sex: "f",
    country: "TW",
    city:"高雄",
    intro:"我是新手請多指教～交友聊天",
    languages:[{lang:"中文", level:"流利"}, {lang:"英文", level:"普通"}],
    sp: "a",
    mainPhoto: "https://loremflickr.com/640/480/taipei,woman/all",
    avatar: "https://loremflickr.com/320/240/taipei,woman/all",
  },
  {
    uid: "default_2019",
    name: "Tracy",
    bday: "1975/02/10",
    sex: "f",
    country: "TW",
    city:"高雄",
    intro:"開心認真的過每一天，喜歡接觸不同的人、事、物～人生就是不斷的成長及學習，希望能與來自不同環境的你、妳共同成長^_^",
    languages:[{lang:"中文", level:"流利"}, {lang:"英文", level:"普通"}],
    sp: "m",
    mainPhoto: "https://loremflickr.com/640/480/taipei,woman/all",
    avatar: "https://loremflickr.com/320/240/taipei,woman/all",
  },
  {
    uid: "default_2020",
    name: "Claire",
    bday: "1981/03/10",
    sex: "f",
    country: "TW",
    city:"高雄",
    intro:"用心做事，用愛成就一切！",
    languages:[{lang:"中文", level:"流利"}],
    sp: "f",
    mainPhoto: "https://loremflickr.com/640/480/taipei,woman/all",
    avatar: "https://loremflickr.com/320/240/taipei,woman/all",
  },
  {
    uid: "default_2021",
    name: "Brenda",
    bday: "1976/04/10",
    sex: "f",
    country: "TW",
    city:"高雄",
    intro:"平凡的女人，期待不平淡的人生～～",
    languages:[{lang:"中文", level:"流利"}, {lang:"英文", level:"普通"}],
    sp: "m",
    mainPhoto: "https://loremflickr.com/640/480/taipei,woman/all",
    avatar: "https://loremflickr.com/320/240/taipei,woman/all",
  },
  {
    uid: "default_2022",
    name: "Mavis",
    bday: "1992/05/10",
    sex: "f",
    country: "TW",
    city:"高雄",
    intro:"抱歉！我不太愛聊天，不過我願意互相交流工作及生活上的事情，如果您是想找炮友，請“勿”留言給我，謝謝！",
    languages:[{lang:"中文", level:"流利"}],
    sp: "f",
    mainPhoto: "https://loremflickr.com/640/480/taipei,woman/all",
    avatar: "https://loremflickr.com/320/240/taipei,woman/all",
  },
  {
    uid: "default_2023",
    name: "Carol",
    bday: "1988/06/10",
    sex: "f",
    country: "TW",
    city:"高雄",
    intro:"不知道該聊什麼...",
    languages:[{lang:"中文", level:"流利"}, {lang:"英文", level:"普通"}],
    sp: "a",
    mainPhoto: "https://loremflickr.com/640/480/taipei,woman/all",
    avatar: "https://loremflickr.com/320/240/taipei,woman/all",
  },
];

export default Recommends;
