# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bacon' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Bacon

  project 'Bacon.xcodeproj'

  platform :ios, '8.0'
  pod 'SDWebImage', '~> 4.0'
  pod 'SDWebImage/WebP'
  pod 'Yoga', path: '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', path: '../node_modules/react-native', subspecs: [
    'BatchedBridge', # Required For React Native 0.45.0+
    'Core',
    'ART',
    'DevSupport'
  ]

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  # pod 'RNVectorIcons'

  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'GooglePlacePicker'

  # Core is always required
  pod 'Firebase/Core'

  # Optional modules
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Storage'

  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'
  # pod 'RNFirebase'

  target 'Bacon-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BaconTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
