# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bacon' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Bacon

  target 'Bacon-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BaconTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'
pod 'RSKImageCropper'
pod 'QBImagePickerController'

[
  'Firebase',
  'Firebase/Core',
  'Firebase/Auth',
  'Firebase/Storage',
  'Firebase/Database',
  'Firebase/RemoteConfig',
  'Firebase/Messaging'
].each do |lib|
  pod lib
end
